#!/usr/bin/env python3

import sys
from impacket import nt_errors
from impacket.smbconnection import SMBConnection, SessionError
from impacket.dcerpc.v5.transport import SMBTransport
from impacket.dcerpc.v5.lsat import DCERPCSessionError, MSRPC_UUID_LSAT, hLsarGetUserName

if len(sys.argv) != 2:
	print(f"Usage: {sys.argv[0]} <IP>")
	sys.exit(1)

RED = '\033[1;31m'
ERROR = '\033[0;31m'
ERROR_ITALIC = '\033[3;31m'
RESET = '\033[0m'

TARGET = sys.argv[1]

is_null = False
is_guest = False
error = ""

# NULL -------
username = ""
password = ""

try:
	conn = SMBConnection(TARGET, TARGET)
except OSError:
	print(f"{ERROR}Connection error{RESET}")
	sys.exit(1)

try:
	conn.login(username, password)
	try:
		tree_id = conn.connectTree("IPC$")
		try:
			file_id = conn.openFile(tree_id, "lsarpc") #srvsvc lsarpc samr
			is_null = True
			conn.closeFile(tree_id, file_id)
		except SessionError as e:
			if e.getErrorCode() == nt_errors.STATUS_ACCESS_DENIED:
				pass
			else:
				print(f"{ERROR}1 NULL: {e}{RESET}")
		conn.disconnectTree(tree_id)
	except Exception as e:
		print(f"{ERROR}2 NULL: {e}{RESET}")
except SessionError as e:
	if e.getErrorCode() == nt_errors.STATUS_ACCESS_DENIED:
		pass
	else:
		print(f"{ERROR}3 NULL: {e}{RESET}")
finally:
	host_netbios = conn.getServerName() if conn.getServerName().rstrip('\x00') else "-"
	domain_netbios = conn.getServerDomain() if conn.getServerDomain().rstrip('\x00') else "-"
	host_dns = conn.getServerDNSHostName().split('.')[0] if conn.getServerDNSHostName().rstrip('\x00') else "-"
	domain_dns = conn.getServerDNSDomainName() if conn.getServerDomain().rstrip('\x00') else "-"

conn.close()

# GUEST -----
username = "Guest"
password = ""

conn = SMBTransport(TARGET, filename="lsarpc", username=username, password=password)
dce = conn.get_dce_rpc()

try:
	dce.connect()
	try:
		dce.bind(MSRPC_UUID_LSAT)
		resp = hLsarGetUserName(dce)
		if resp['UserName'] != 'Anonymous Logon':
			is_guest = True
	except DCERPCSessionError as e:
		print(f"{ERROR}1 GUEST: {e}{RESET}")
	dce.disconnect()
except OSError:
	print(f"{ERROR}Connection error{RESET}")
	sys.exit(1)
except SessionError as e:
	if e.getErrorCode() == nt_errors.STATUS_ACCOUNT_DISABLED:
		#error = f"{ERROR}(Policy: {ERROR_ITALIC}Accounts: Guest account status{ERROR}){RESET}"
		pass
	elif e.getErrorCode() == nt_errors.STATUS_LOGON_TYPE_NOT_GRANTED:
		#error = f"{ERROR}(Policy: {ERROR_ITALIC}Deny access to this computer from the network{ERROR}){RESET}"
		pass
	elif e.getErrorCode() == nt_errors.STATUS_LOGON_FAILURE:
		#error = f"{ERROR}(Guest account needs password OR guest disabled and account name changed{RESET}"
		pass
	else:
		print(f"{ERROR}2 GUEST: {e}{RESET}")

# OUTPUT -------
print(f"NetBIOS computer name\t: {RED}{host_netbios}{RESET}")
print(f"NetBIOS domain name\t: {RED}{domain_netbios}{RESET}")
print(f"DNS host name\t\t: {RED}{host_dns}{RESET}")
print(f"DNS domain name\t\t: {RED}{domain_dns}{RESET}")
print()
print("Null session\t\t:", f"{RED}YES{RESET}" if is_null else "NO")
print("Guest logon\t\t:", f"{RED}YES{RESET}" if is_guest else f"NO {error}")
